### ISSUE TITLE
Multiple URLs for same view.

### ISSUE THREAD

**Issue by dhruvhacks** [ishneetknarang/Attendance_Module#12]
https://github.com/ishneetknarang/Attendance_Module/blob/14087f0940adadc23e87ba971d13efeaac8889df/student_attendance/urls.py#L23
and
https://github.com/ishneetknarang/Attendance_Module/blob/14087f0940adadc23e87ba971d13efeaac8889df/student_attendance/urls.py#L22
are pointing at same view.

Remove one of them.

**Comment by ishneetknarang** [comment]
done sir

**Comment by dhruvhacks** [comment]
@ishneetknarang Push the changes on repository.
