### ISSUE TITLE
Use relevant commit messages.

### ISSUE THREAD

**Issue by dhruvhacks** [ishneetknarang/Attendance_Module#5]
You have used commit message as ```abc``` for commit ```d33267df``` and ```2e77d34```.
This is a bad way of writing commit messages.

Refer [link](https://github.com/erlang/otp/wiki/writing-good-commit-messages)

**Comment by ishneetknarang** [comment]
okay sir , now onwards i will this in mind.

**Comment by dhruvhacks** [comment]
@ishneetknarang but you still used 'Attendance' as your commit messages as observed in #15 
Relevant commit messages tell what this commit includes. e.g. "initial commit", "dashboard views added", "urls updated", "db removed" etc. For standard ways of writing commit messages, refer [link](https://chris.beams.io/posts/git-commit/).
